const levels = [
  { name: "A0", color: "lightBlue" },
  { name: "A1.2", color: "green" },
  { name: "A2.2", color: "yellow" },
  { name: "A2.3", color: "green" },
  { name: "B1.1", color: "aqua" },
  { name: "B1.2", color: "orange" },
  { name: "B1.3", color: "beige" },
  { name: "B2.1", color: "lightBlue" },
  { name: "B2.2", color: "green" },
  { name: "B2.3", color: "yellow" },
  { name: "B2.4", color: "red" },
  { name: "B2/C1", color: "aqua" },
  { name: "C1.1", color: "orange" },
  { name: "C1.2", color: "lightBlue" },
  { name: "C1.3", color: "green" },
  { name: "C1.4", color: "yellow" },
  { name: "C1.5", color: "red" },
  { name: "C1.6", color: "aqua" },
  { name: "C1.7", color: "orange" },
  { name: "C1.8", color: "beige" },
];
